### ISSUE TITLE
Animal Buddy HUD icon objects can fill up multiple object slots, preventing others from spawning

### ISSUE THREAD

**Issue by Mattrizzle** [H4v0c21/DKC-2-Project-Kongs#32]
Likely due to the change in how DK Barrels work, breaking a DK Barrel while transformed into an Animal Buddy with one Kong in reserve will spawn another Animal Buddy HUD icon without despawning the existing one. Eventually, this results in other objects not spawning properly (in my case, a Kannon that makes it easier to cross a gap).

**Comment by Mattrizzle** [comment]
Do you think it would be a good idea to make DK Barrels behave as they do in the original game if transformed into an Animal Buddy?  This issue occurs because they are always active, and breaking a DK Barrel in this state doesn't change which Kongs you will have after transforming back anyway.

**Comment by H4v0c21** [comment]
That sounds like a good idea. I can take this one if you want.

**Comment by Mattrizzle** [comment]
If you don't mind, since you've already been deep into that DK Barrel logic!
