### ISSUE TITLE
DK Barrels go through the incorrect cycle if Diddy and Kiddy are active

### ISSUE THREAD

**Issue by Mattrizzle** [H4v0c21/DKC-2-Project-Kongs#37]
If Diddy and Kiddy are active, the DK Barrel cycle is Dixie, Donkey, Diddy, just as it is with Kiddy alone.

**Comment by H4v0c21** [comment]
This bug is probably due to an oversight by me when coding the barrel swap code. There probably needs to be additional checks when the kong number rolls over to 0.
I've also marked this as a bug and added it to core engine stability because it causes a soft lock. I'll try to fix it ASAP

**Comment by Mattrizzle** [comment]
That was fast! I think we're good to close this issue.
