### ISSUE TITLE
Invulnerability timers aren't cleared for Donkey or Kiddy at level load

### ISSUE THREAD

**Issue by Mattrizzle** [H4v0c21/DKC-2-Project-Kongs#38]
Exiting a level using Start+Select while Donkey or Kiddy Kong are in their flashing invulnerable state after being hit and entering a level again will result in either Kong still being in their invulnerable state.

**Comment by H4v0c21** [comment]
Something similar happens with the ! invincibility barrels for Donkey and Kiddy.
If you break a ! barrel then start+select you will remain invulnerable in any level you enter until the timer runs out.

**Comment by Mattrizzle** [comment]
This is resolved!  Closing it now.
