### ISSUE TITLE
Crash occurs just past the first tire in Jungle Jinx

### ISSUE THREAD

**Issue by Mattrizzle** [H4v0c21/DKC-2-Project-Kongs#56]
It isn't immediately obvious whether or not a specific object is causing it, but it does happen consistently when moving past a certain point.

**Comment by Mattrizzle** [comment]
It's one of the tire objects.  The object init scripts really need to be combed through to replace the static values with labels where applicable.  Several of the if !version statements are suspect, as they contain commands with parameters that are pointers.

**Comment by Mattrizzle** [comment]
Possibly related to Issues #9, #34, and #49.

**Comment by H4v0c21** [comment]
This issue was the same exact cause for many of the early crashes related to objects spawning. I'll start working on making all the pointers dynamic.
