### ISSUE TITLE
Possible palette overflow in Target Terror

### ISSUE THREAD

**Issue by H4v0c21** [H4v0c21/DKC-2-Project-Kongs#62]
Partially into the level a DK barrel with the incorrect palette can be encountered. Bananas and other hud elements also display this behavior.

**Comment by Mattrizzle** [comment]
It's definitely a palette overflow, and I suspect that the changing DK Barrel palette is causing it.  Near the Continue Barrel in the vanilla game, all 8 sprite palettes are used.  The DK Barrel tries to add a ninth.

One possible solution is to remap the gates used throughout the level to the barrel palette:
![image](https://user-images.githubusercontent.com/107769367/233841781-e6d68db4-44fa-4203-80bf-dd02d1983266.png)
It's noticeably darker when they're placed side by side like this, but perhaps it will be less apparent in-game.

**Comment by H4v0c21** [comment]
I think that's a good solution. If you showed me the darker one I would have thought it was always like that.
