### ISSUE TITLE
kong_status persists between players in 2 Player Contest

### ISSUE THREAD

**Issue by H4v0c21** [H4v0c21/DKC-2-Project-Kongs#69]
This causes the other player's kongs to match the previous ones due to the fact that kong_status overrides the vanilla kong number.
For example if player 1 has Donkey and Diddy when the game swaps to player 2's save they will also have Donkey and Diddy regardless of which kongs they had previously.

**Comment by Mattrizzle** [comment]
This might be resolved as of the latest pull request: #78
