### ISSUE TITLE
 Failed to build, tested with all versions of asar.exe

### ISSUE THREAD

**Issue by Maatooh** [H4v0c21/DKC-2-Project-Kongs#79]
asar.exe -Dversion=1 -Dtimestamp="2023-11-05 19:38" "source\all.asm" dkc2_1.1.sfc
source/ram.asm:19: error: (E5063): Setting labels to each other is not valid. [spr_view_pal1_val = spr_view_pal1_loc+2]
source/ram.asm:20: error: (E5063): Setting labels to each other is not valid. [spr_view_pal2_loc = spr_view_pal1_loc+4]
source/ram.asm:21: error: (E5063): Setting labels to each other is not valid. [spr_view_pal2_val = spr_view_pal1_loc+6]
source/ram.asm:22: error: (E5063): Setting labels to each other is not valid. [spr_view_layer_toggle = spr_view_pal1_loc+8]
source/all.asm:85: error: (E5153): Invalid check command. [check bankcross full]
source/graphics_part_1.asm:445: error: (E5061): Label 'title_screen_tilemap' redefined. [title_screen_tilemap:]
source/graphics_part_1.asm:449: error: (E5061): Label 'title_screen_tiledata' redefined. [title_screen_tiledata:]
source/graphics_part_1.asm:752: error: (E5153): Invalid check command. [check bankcross full]
source/sound.asm:4195: error: (E5153): Invalid check command. [check bankcross full]
source/bank_f8.asm:16: error: (E5061): Label 'nintendo_copyright_tilemap' redefined. [nintendo_copyright_tilemap:]
source/all.asm:209: error: (E5153): Invalid check command. [check bankcross full]
source/kong_hack/objects/graphics/donkey_sprite_data.asm:1: error: (E5153): Invalid check command. [check bankcross full]
source/kong_hack/objects/graphics/kiddy_sprite_data.asm:1: error: (E5153): Invalid check command. [check bankcross full]
source/bank_80.asm:1994: error: (E5060): Label 'vram_intro_block_1' wasn't found. [LDA #vram_intro_block_1]
source/bank_80.asm:1996: error: (E5060): Label 'vram_intro_block_2' wasn't found. [LDA #vram_intro_block_2]
source/bank_80.asm:1998: error: (E5060): Label 'vram_intro_block_3' wasn't found. [LDA #vram_intro_block_3]
source/bank_80.asm:2000: error: (E5060): Label 'vram_intro_block_4' wasn't found. [LDA #vram_intro_block_4]
source/bank_80.asm:2010: error: (E5060): Label 'intro_nintendo_presents_tilemap' wasn't found. [LDA #intro_nintendo_presents_tilemap]
source/bank_80.asm:2021: error: (E5060): Label 'vram_intro_mini_rare_logo_tilemap' wasn't found. [LDA #vram_intro_mini_rare_logo_tilemap]
source/bank_80.asm:2031: error: (E5060): Label 'vram_intro_unknown' wasn't found. [LDA #vram_intro_unknown]
source/bank_80.asm:2041: error: (E5060): Label 'vram_intro_unknown2' wasn't found. [LDA #vram_intro_unknown2]
source/bank_80.asm:2041: error: (E5001): Over 20 errors detected. Aborting. [LDA #vram_intro_unknown2]
A fatal error was detected while assembling the patch. Assembling aborted. Your ROM has not been modified.

Please, thanks!

**Comment by H4v0c21** [comment]
Hello, can you list the versions of asar used?

**Comment by Maatooh** [comment]
Greetings, I have tried these versions.

Asar v1.50
Asar v1.61
Asar v1.71
Asar v1.80
Asar v1.81

**Comment by H4v0c21** [comment]
Project Kongs uses Asar v1.90pre. Currently you must compile the version from source using this branch of asar: https://github.com/RPGHacker/asar/tree/asar_19. An ips patch will be available soon. Marking the issue resolved.

**Comment by Maatooh** [comment]
It works, thank you very much!
