### ISSUE TITLE
Sometimes player doesn't pick up bananas from hand slap

### ISSUE THREAD

**Issue by H4v0c21** [H4v0c21/DKC-2-Project-Kongs#84]
The banana should always move to the player and get collected, sometimes it doesn't and just stops near the player.

**Comment by BlueImp78** [comment]
Didn't notice it right away but after some testing, this issue was fixed in this commit: [75009b9](https://github.com/H4v0c21/DKC-2-Project-Kongs/commit/75009b9e724f8bac1479905c4542c6d6a9722697)
