### ISSUE TITLE
Kiddy Kong uses Diddy's hit and death animation

### ISSUE THREAD

**Issue by Robotboy13** [H4v0c21/DKC-2-Project-Kongs#99]
When Kiddy gets hit he turns into a blue Diddy using his animations. I hope when there is a public release of this hack his death and hurt sprite will be fixed using his DKC3 animations where he cries like a baby.

**Comment by Robotboy13** [comment]
The rom I'm using was from here https://www.snesforever.com.br/2024/02/dkc-2-project-kongs.html

**Comment by H4v0c21** [comment]
You are using an older build of the hack that leaked online many months ago. Please avoid reporting issues if you aren't running the latest build. This has already been fixed in the official build.
